name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    uses: lifesystemsufpr/devops-hub/.github/workflows/ci-node-frontend.yml@main
    with:
      node-version: '22'
      package-manager: 'pnpm'
      coverage-threshold: 40
      next-app: true
    secrets: inherit
